// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ruzdi_DB.Context;

#nullable disable

namespace Ruzdi_DB.Migrations
{
    [DbContext(typeof(DB_Ruzdi))]
    [Migration("20220910182359_For_create_DB")]
    partial class For_create_DB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NotificationPledgor", b =>
                {
                    b.Property<string>("NotificationsId")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("PledgorsId")
                        .HasColumnType("varchar(95)");

                    b.HasKey("NotificationsId", "PledgorsId");

                    b.HasIndex("PledgorsId");

                    b.ToTable("NotificationPledgor");
                });

            modelBuilder.Entity("Ruzdi_DB.Entityes.Contracts", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(95)");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("TermOfContract")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("Ruzdi_DB.Entityes.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("ContractsID")
                        .IsRequired()
                        .HasColumnType("varchar(95)");

                    b.Property<DateTime?>("DataTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Error")
                        .HasColumnType("longtext");

                    b.Property<string>("NumberNotification")
                        .HasColumnType("longtext");

                    b.Property<string>("Packageguid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Packageid")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TypeNotification")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ZipArchive")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("registrationCertificateId")
                        .HasColumnType("varchar(95)");

                    b.HasKey("Id");

                    b.HasIndex("ContractsID");

                    b.HasIndex("registrationCertificateId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Ruzdi_DB.Entityes.Pledgor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Pledgor");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Pledgor");
                });

            modelBuilder.Entity("Ruzdi_DB.Entityes.Regions", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("CodeRegion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("Ruzdi_DB.Entityes.RegistrationCertificate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("documentAndSignature")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("RegistrationCertificate");
                });

            modelBuilder.Entity("Ruzdi_DB.Entityes.Organizations", b =>
                {
                    b.HasBaseType("Ruzdi_DB.Entityes.Pledgor");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("INN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameFull")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OGRN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RegionId")
                        .HasColumnType("varchar(95)")
                        .HasColumnName("Organizations_RegionId");

                    b.HasIndex("RegionId");

                    b.HasDiscriminator().HasValue("Organizations");
                });

            modelBuilder.Entity("Ruzdi_DB.Entityes.Persons", b =>
                {
                    b.HasBaseType("Ruzdi_DB.Entityes.Pledgor");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("First")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Last")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Middle")
                        .HasColumnType("longtext");

                    b.Property<string>("PersonDocument")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasColumnType("varchar(95)");

                    b.HasIndex("RegionId");

                    b.HasDiscriminator().HasValue("Persons");
                });

            modelBuilder.Entity("NotificationPledgor", b =>
                {
                    b.HasOne("Ruzdi_DB.Entityes.Notification", null)
                        .WithMany()
                        .HasForeignKey("NotificationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ruzdi_DB.Entityes.Pledgor", null)
                        .WithMany()
                        .HasForeignKey("PledgorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ruzdi_DB.Entityes.Notification", b =>
                {
                    b.HasOne("Ruzdi_DB.Entityes.Contracts", "PledgeContract")
                        .WithMany("Notifications")
                        .HasForeignKey("ContractsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ruzdi_DB.Entityes.RegistrationCertificate", "registrationCertificate")
                        .WithMany()
                        .HasForeignKey("registrationCertificateId");

                    b.Navigation("PledgeContract");

                    b.Navigation("registrationCertificate");
                });

            modelBuilder.Entity("Ruzdi_DB.Entityes.Organizations", b =>
                {
                    b.HasOne("Ruzdi_DB.Entityes.Regions", "Region")
                        .WithMany("Organizations")
                        .HasForeignKey("RegionId");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Ruzdi_DB.Entityes.Persons", b =>
                {
                    b.HasOne("Ruzdi_DB.Entityes.Regions", "Region")
                        .WithMany("Persons")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Ruzdi_DB.Entityes.Contracts", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Ruzdi_DB.Entityes.Regions", b =>
                {
                    b.Navigation("Organizations");

                    b.Navigation("Persons");
                });
#pragma warning restore 612, 618
        }
    }
}
